{% set name = "kanga" %}
{% set version = "0.0.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: enter-sha256-key-here

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib >=3.3.3
    - numpy >=1.19.2
    - python
    - scipy >=1.5.2
    - seaborn >=0.11.0
    - statsmodels >=0.12.0

test:
  imports:
    - kanga
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/papamarkou/kanga"
  license: MIT
  license_file: LICENSE.txt
  summary: "MCMC diagnostics"

extra:
  recipe-maintainers:
    - papamarkou
