{% set name = "kanga" %}
{% set version = "0.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 063d19d5772cca87a06651fba0be85dbdbaba97f9cc385c25f872bff16ded44f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base >=3.3.3
    - numpy >=1.19.2
    - python
    - scipy >=1.5.2
    - seaborn >=0.11.0
    - statsmodels >=0.12.0

test:
  imports:
    - kanga
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/papamarkou/kanga
  summary: MCMC diagnostics
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - papamarkou
